model: 'MLPGraphReg'
num_layers: 8
hidden_dim: 220
residual: True
batch_norm: True
readout: 'sum'
dropout: 0.1 #CHANGE TO BEST
weight_decay: 0.001 #CHANGE TO BEST
batch_size: 128
epochs: 1200 #change to 1200
init_lr: .001
# lr_factor: 0.5
# lr_patience: 10
min_lr: .00001
use_counts: True
count_type: 'both'
count_files: ['zinc_with_homs_c7.json', 'zinc_with_homs_c8.json']
idx_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 17, 18, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46]
description: 'MLP with 78 cycle basis'
debug: False
scheduler: "CosineAnnealingLR"
lr_warmup: True