out_dir: results
metric_best: mae
metric_agg: argmin
#seed: 15 #EDITTED FOR TEST
wandb:
  use: True
  project: QM9_GPS1
  group: medium #EDITTED FOR TEST
dataset:
  format: EmJ-QM9-GraphHC
  name: GAP
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: MLPNodeEnc
  node_encoder_init_dim: 15
  node_encoder_hid_dim: 64
  node_encoder_depths: 2
  node_encoder_bn: True
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 5
  edge_encoder_bn: False
  graph_encoder: True
  graph_encoder_name: GraphCountEnc
ctenc_GraphCountEnc:
  raw_bn: False
  dim_ogct: 31
  dim_hid: 36
  dim_ct: 36
  n_layers: 2
  dropout: 0.0
  norm: batch_norm
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GINE+Transformer  # CustomGatedGCN+Performer
  layers: 10
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  head_misc: #temp fix
    hidden_layers: 2
    use_graphHC: True
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 1e-3
  base_lr: 0.001
  max_epoch: 5000 #CHANGE 
  scheduler: custom_cosine_with_warmup #orginally cosine_with_warmup
  num_warmup_epochs: 10
