out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC_treehom2
  group: SA-none_gs1
dataset:
  format: PyG-ZINC-WLtree_full
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+NodeCountEnc
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
ctenc_NodeCountEnc:
  raw_bn: False
  dim_ogct: 85
  dim_hid: 85
  dim_ct: 16
  n_layers: 2
  dropout: 0.0
  norm: batch_norm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  enforce_param_budget: true
  param_budget: 500000
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: None+Transformer  # CustomGatedGCN+Performer
  layers: 2
  n_heads: 8
  dim_hidden: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
  varied_width: True
  initial_depth: 1
  dim_initial: 200
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 800 #GS on 800 cuz it should remain lower than 3hrs for all feature enchancements (can do final runs on a more epochs)
  scheduler: cosine_with_warmup
  num_warmup_epochs: 20 #change back to 50 if you use all 2000 epochs
