out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC_treehom2
 # group: initial_MLP
  group: MLPwl-none_repeats2
dataset:
  format: PyG-ZINC-WLtree_full
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+NodeCountEnc
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
ctenc_NodeCountEnc:
  raw_bn: False
  dim_ogct: 17
  dim_hid: 24
  dim_ct: 24
  n_layers: 2
  dropout: 0.0
  norm: batch_norm
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: MLPGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
mlp:
  layers: 8
  dim_hidden: 156
  residual_connection: True
  batch_norm: True
  dropout: 0.1
  head: san_graph
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 1e-3
  base_lr: 0.001
  max_epoch: 1200
  scheduler: custom_cosine_with_warmup #orginally cosine_with_warmup
  num_warmup_epochs: 10
