out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: ZINC_treehom
  group: SAwl-pe+hc_repeats
dataset:
  format: PyG-ZINC-Spasm+WLtree
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+NodeCountEncX2+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: mlp_flat
  dim_pe: 8
  raw_norm_type: BatchNorm
  layers: 2
  norm: "batch_norm"
ctenc_NodeCountEncX2:
  dim_ct: 18
  spasm:
    raw_bn: False
    dim_ogct: 42
    dim_hid: 28
    dim_ct: 12
    n_layers: 2
    dropout: 0.0
    norm: batch_norm
  wl:
    raw_bn: False
    dim_ogct: 17
    dim_hid: 12
    dim_ct: 6
    n_layers: 2
    dropout: 0.0
    norm: batch_norm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  enforce_param_budget: true
  param_budget: 500000
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: None+Transformer  # CustomGatedGCN+Performer
  layers: 12
  n_heads: 4
  dim_hidden: 44  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 44  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 2000 #GS on 900 cuz it should remain lower than 3hrs for all feature enchancements (can do final runs on a more epochs)
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50 #change back to 50 if you use all 2000 epochs
