out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: synth-3-MLP
  group: synth-MLP-all5-avgClus
dataset:
  format: EmJ-Synth-All5
  name: AvgClust
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: MLPNodeEnc
  node_encoder_init_dim: 30
  node_encoder_hid_dim: 64
  node_encoder_depths: 2
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: MLPGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
mlp:
  layers: 8
  dim_hidden: 64
  residual_connection: True
  batch_norm: True
  dropout: 0.1
  head: san_graph
optim:
  clip_grad_norm: False
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 1200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 30