out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: test
  group: new_ssh
dataset:
  format: EmJ-QM9-NodeHC
  name: GAP
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: MLPNodeEnc+NodeCountEnc+RWSE
  node_encoder_init_dim: 15
  node_encoder_hid_dim: 64
  node_encoder_depths: 2
  node_encoder_bn: True
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 5
  edge_encoder_bn: False
  graph_encoder: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: mlp_flat
  dim_pe: 28
  raw_norm_type: BatchNorm
  layers: 2
  norm: "batch_norm"
ctenc_NodeCountEnc:
  raw_bn: False
  dim_ogct: 31
  dim_hid: 36
  dim_ct: 36
  n_layers: 2
  dropout: 0.0
  norm: batch_norm
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: MLPeGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
mlp:
  layers: 4
  dim_hidden: 220
  residual_connection: True
  batch_norm: True
  dropout: 0.1
  head:
    type: san_graph
    hidden_layers: 2
    use_graphHC: False
  edge_encoder:
    layers: 2
    dim_hidden: 32
    residual_connection: True
    batch_norm: True
    dropout: 0.1
  graph_encoder:
    layers: 3
    dim_hidden: 260
    residual_connection: True
    batch_norm: True
    dropout: 0.1
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 1e-3
  base_lr: 0.001
  max_epoch: 2 
  scheduler: custom_cosine_with_warmup #orginally cosine_with_warmup
  num_warmup_epochs: 10
